version: "3.9"

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    command:
      - --auth
      #- --bind_ip localhost # (0.0.0.0)

  # NextJS
  app:
    build: . # build Dockerfile which is present in the same directory
    restart: always
    ports:
      - "3000:3000"
      - "80:80"
    environment:
      STATE: production
      MONGODB_URI: mongodb://applicationUser:sample-Password@mongodb:27017/taco-blog # mongodb://<service-name>:<port>/
      DB_NAME: taco-blog
      TOKEN_SECRET: journalTokenSuperSecret
    depends_on:
      - mongodb

volumes:
  mongodb: {}